---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
    assignees:
      - groveld

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 1
    groups:
      npm:
        patterns:
          - "*"
    cooldown:
      default-days: 7
    assignees:
      - groveld
