FROM ruby:alpine

LABEL com.github.actions.name="Build Container"
LABEL com.github.actions.description=""
LABEL com.github.actions.icon="code"
LABEL com.github.actions.color="red"
LABEL repository=""
LABEL maintainer="Martin Groeneveld <martin@groveld.com>"

ENTRYPOINT ["/action/lib/entrypoint.sh"]
